
server:
  port: 8080



spring:
  cloud:
    gateway:
      routes:
        - id: patient-service-route
          uri: http://patient-service:9010
          predicates:
            - Path=/api/patients/**
          filters:
            - StripPrefix=1


        - id: api-docs-patient-route
          uri: http://patient-service:9010
          predicates:
            - Path=/api-docs/patients
          filters:
            - RewritePath=/api-docs/patients,/v3/api-docs


        - id: auth-service-route
          uri: http://auth-service:9050
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1

